### ISSUE TITLE
crash when app start from background. Receiver not registered: com.ninty.system.setting.SystemSetting

### ISSUE THREAD

**Issue by pppppppppppp12** [c19354837/react-native-system-setting#49]
**Steps to reproduce the issue**
1. start the app
2. back button, exit app
3. enter app, setVolume, then app will crash

**Error log**
Receiver not registered: com.ninty.system.setting.SystemSetting
setVolume -> SystemSetting.java

**More error log**
java.lang.IllegalArgumentException: Receiver not registered: com.ninty.system.setting.SystemSetting$1@4247e2a0
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:748)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1647)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at com.ninty.system.setting.SystemSetting.setVolume(SystemSetting.java:274)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:515)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:808)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
08-03 09:30:52.258  8730  8783 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:848)

**Comment by c19354837** [comment]
Thanks for your feedback. I need your phone info.

**Comment by pppppppppppp12** [comment]
android 4.4.4, android 5.0, android 7.0. Maybe both in android?

**Comment by c19354837** [comment]
I cannot reproduce in Android 5, and I test it by [example](https://github.com/c19354837/react-native-system-setting/tree/master/examples/SystemSettingExample).
