### ISSUE TITLE
Crash on android from fabric

### ISSUE THREAD

**Issue by chenyifan88** [c19354837/react-native-system-setting#70]
OPPO R7Plust Android: 5.0

Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.mrlu/com.mrlu.MainActivity}: java.lang.RuntimeException: java.lang.IllegalArgumentException: Receiver not registered: com.ninty.system.setting.SystemSetting$VolumeBroadcastReceiver@81fac47
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3646)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3601)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3576)
       at android.app.ActivityThread.access$1200(ActivityThread.java:195)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5856)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by c19354837** [comment]
I fixed a similar bug in V 1.5.3, so which version are you using?
